multibootusb
If the USB disk has a label with spaces inside (for example 
"/run/media/spahan/BOOT DISK/multibootusb/syslinux.cfg") 
it fails to properly open the file if you press "Edit" in the Syslinux panel.
Adding quotes to the path fixes the issue.
=> quote syslinux.cfg path to avoid trouble with spaces

scripts/syslinux.py
The syslinux executable only works for FAT, not NTFS. So the solution here is to
use extlinux for it instead. This fixes NTFS usage on GNU/Linux.
=> Use extlinux for NTFS.

scripts/usb.py
I've noticed when I start up the application with my external USB drive connected with the following mount point: 
```
/media/chris/Toshiba Canvio
```
The application would crash saying essentially "No mount point found at `/media/chris/Toshiba`". Then I looked at the source code and quickly noticed that mount points were found by piping the output of `mount` and `cut`ting by a space. So I did some research and found that a better command would be:
```
findmnt -nr -o target -S
```
which returns the only mount point as the output. See [this StackExchange post](http://unix.stackexchange.com/questions/34718/is-there-a-command-to-see-where-a-disk-is-mounted/217412#217412).
Now the application does not crash upon startup. 
Thanks to all those who helped built this awesome application!
=> Fix crash when mount point has whitespace

install.py
On Ubuntu 16.04 alias Xenial mutlibootusb also required `python-dbus` to
run properly.
This is only tested on Ubuntu 16.04, but I checked whether Debian also provides a `python-dbus` package.
=> Added `python-dbus` to `apt-get` packages

data/multibootusb.desktop
Since the icon already is installed to a location compliant with [freedesktop.org standards](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) you don't need to specify the full icon path (neither the file type extension) in the launcher. 
The icon will be found anyway.
This facilitates icon theming.
Cf. this [example `.desktop` launcher](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example) presented in the freedesktop.org documentation.
=> Unhardcode icon file type in GNU/Linux laucher

scripts/usb.py
The devices returned by list_devices() may not always have all the
properties and referencing them raises a KeyError. Use the .get()
interface as suggested by the upstream[0] to avoid such exceptions.
[0] http://pyudev.readthedocs.io/en/latest/guide.html#id6
=> scripts/usb.py: use device.get() instead of device[''] to handle KeyError

build_pkg, scripts/usb.py
Take advantage of upstream's bugfixes in pyudev.
(Not removing the bundled pyudev files just yet)
=> linux: use system pyudev library instead of bundled

scripts/syslinux.py
Executing ==>
dd if=/dev/sdb1 of=/media/user/USBFLASH"/media/user/USBFLASH/multibootusb/debian/isolinux/debian-install.bs" count=1
dd: failed to open '/media/user/USBFLASH/media/user/USBFLASH/multibootusb/debian/isolinux/debian-install.bs':
No such file or directory
Failed to install syslinux on distro directory...
=> Fix installing syslinux in distro dir on ext2/3/4

scripts/usb.py
Don't rely on ID_USB udev item for "All devices"
Should fix #110
=> linux: rethink device detection logic

scripts/config.py
xdg-open launches the user's default text editor defined 
on the current desktop environment for text/plain mimetype
=> linux: try to use default text editor first

multibootusb
There were some typos and formatting problems in the usage information -- this commit fixes them.  Also, wherever commands intended to be typed into a terminal are given in the usage information, I made sure to clearly separate them from explanatory text.  I also changed the text at the top of the file about licensing, because "v.2" could be interpreted as "version 0.2" which doesn't exist.
=> Clean up usage info string

scripts/syslinux.py
Given issues installing syslinux on NTFS, this commit changes the chosen bootloader to extlinux, as per http://www.syslinux.org/archives/2012-December/019151.html
=> Reapplied upstream PR #26

scripts/gen.py, scripts/qemu.py, scripts/syslinux.py, scripts/usb.py
get_physical_disk_number() can fail on non-English version of Windows because the value of partition.Caption obtained via wmi.WMI().Win32_DiskDrive() is locale dependent.
=> Fixing dependency of get_physical_disk_number() on locale setting.

scripts/gen.py, scripts/usb.py
The change should make what's being performed more explicit and avoid having a console window popping up.
=> Have gpt_device() use 'wmi' module rather than spawn diskpart.exe

.gitignore, build_pkg, build_pkg_path.json.template
Allow paths such as 'pyinstaller_dir' or 'release_dir' to be configured outside of 'build_pkg' script so that conflict on the path setting code block can be avoided. Currently paths are read out of 'build_pkg_path.json' file. If the file is not present, setting in the script will be used.
=> Allow setting of build related paths in an external file.

scripts/gen.py, scripts/install.py, scripts/uninstall_distro.py
I'm trying to introduce a developer switch, with which distro files on usb stick are not deleted when the distribution is removed so that debugging will be less time-consuming.
=> Simplify code by eliminating common expression.

scripts/grub.py
For example, isolinux.cfg on trinity resuce cd has the following line:
> append vollabel=No_label initrd=initrd.trk ramdisk_size=65536 root=/dev/ram0 vga=788 splash=verbose pci=conf1 trkmenu
The original regular expression catches 'label' in 'vollabel=No_label'.
Performed code cleanup as well. Please note that https://github.com/mbusb/multibootusb/commit/b437771c2e665df5629bd83b09a337d02d5ef536 not only adjust indentation level but also replaces 'm.group().lower()' with 'matched'.
=> Fix issue of 'menu label' or 'label' matching in the middle of line.

scripts/_7zip.py, scripts/install.py, scripts/iso.py
Allow one pass execution of multi patterned file extraction.
Make use of copy_iso() function and add '/Y' to xcopy command and an assert to prevent a hang.
Remove redundant membership check before iterating over the members.
=> Allow one pass execution of multi patterned file extraction.

scripts/grub.py, scripts/install.py, scripts/mbusb_gui.py
Tested with following distributions. At least one menu item booted via grub successfully with the exception of dban. Dban hang during boot and I'm not brave enough to try further.
- antergos-18.3-x86_64
- debian-live-9.4.0-amd64-cinnamon
- dban-2.3.0_i586
- Fedora-Workstation-Live-x86_64-27-1.6
- kali-linux-light-2018.1-amd64
- MorpheusArchLinux-20-01-17-2017.01.20-dual
- kubuntu-18.04-beta1-desktop-amd64
- ubuntu-17.10.1-desktop-amd64
- linuxmint-18.3-kde-64bit
- clonezilla-live-2.5.2-31-amd64
=> More fixes on syslinux installation and loopback.cfg generation.

scripts/update_cfg_file.py
part in 'initrd.img' gets affected.
Now salixlive-xfce-14.2.1 boots but sadly /init fails to mount live media. It seems fromiso= parameter is not honored anymore.
=> Fix tweaking of 'initrd=...' line keyed on 'initrd' because 'initrd'

scripts/grub.py, scripts/iso.py
With the change in the commit, loopback.cfg got regenerated at the
location of file determined by scanning iso tree. If no loopback.cfg was
available, new one got generated at the distribution tree root. In ether
case, loopback.cfg was always chosen for booting.
Now, if no loopback.cfg is found, grub.cfg is sought. It is only in the
case where neither is found that loopback.cfg gets generated and used.
=> Fix regression introduced by 8ea5932bdcd706d7ca4c8b44aa7b0a424daec59d.

scripts/_7zip.py, scripts/distro.py, scripts/mbusb_gui.py
executable.
Remove repeated call to _7zip.list_iso(iso_link)
Adjusted line breaking to fit within 80 columns.
=> Detect running 7zip on a currupted iso as well as the lack of 7z

scripts/install.py
distros that have some dirs relocated to the root dir.
This error does not get triggered in normal situation. It manifests if installation is tried after unsuccessful uninstallation.
=> Fix module name typo that gets triggered by overwriting installation of

scripts/mbusb_gui.py, scripts/uninstall_distro.py
because config.distro gets overwritten during uninstallation.
Here is a way to reproduce the issue.
1. install an arch variant.
2. select a debian variant iso.
3. uninstall the arch variant.
4. click 'install'
5. mbusb tries to install the debian variant assuming 'arch'.
* Fix missed call to update_list_box() when performing config-files-only
uninstallation, which happens because distro dir is already gone.
* Fix missed update of grub.cfg when performing config-files-only
uninstallation.
* Fix multiple calls to delete_frm_file_list() when uninstalling
'windows', 'alpine' and 'generic'.
* Fix multiple calls to update_sys_cfg_file() when uninstalling a distro.
* Escape distro name when using it within regular expressions.
* Adjust line breaking to fit 80 cols.
=> * Fix distro detection going out of sync after uninstalling a distro

scripts/distro.py, scripts/install.py, scripts/param_rewrite.py, scripts/persistence.py, scripts/update_cfg_file.py
* Fix a rather critical bug in 'ConfigTweaker.tweak_first_match()' that got 'param_operation' contaminated with 'param_operations_for_persistence' as the recursion progress.
* Support CentOS DVD installers. Tested with CentOS-7-x86_64-(DVD/Minimal/NetInstall)-1708.iso  (Full install DVD requires ext3 formatted usb stick because its size exceeds 4GB.)
* Straighten CentOS Live DVD support. (Those were recognized as 'fedora' before this fix.)
* Fix 'add_op_if_file_exists()' to properly handle '/' prefixed to a path.
* Reorgazined Twaker classes a bit.
* Removed control chars and extra spaces in test inputs.
=> Fix bug in a ConfigTweaker method & Add CentOS 7 Installer DVD support

scripts/grub.py, scripts/install.py, scripts/update_cfg_file.py
**This PR may conflict with another pending PR. If so, please let me know.
I'll replace this PR with a new one.**
* Prefer 'grub.cfg' over other variants like 'grub-embedded.cfg'
* Extract the tree rooted at EFI/ as well.
* Probe .txt files other than 'thema.txt' for rewriting desktop-image:
setting.
* Add 'legacy_tweak()' method to ConfigTweakers to keep old behaviour.
* Add SalixConfigTweaker.
=> Add Support for WifiSlax64-1.1-final

scripts/update_cfg_file.py
Got an exception when installing _debian-9.4.0-amd64-netinst.sio_
because f.readlines() tried to convert utf-8 encoded text  to unicode assuming cp-932.
Now force utf-8 when opening target files.
Perform update only if disktop-image path was successfully tweaked.
=>  Fix exception from opening utf-8 encoded text file

scripts/distro.py, scripts/grub.py, tests/test-grub.py
* Deal with syslinux config file lacking 'kernel' line.
* Fix misdetection as 'centos'
Also contains improvement of kernel/initrd path rewriting.
=> Get salitaz-rolling rolling again.

scripts/distro.py, tests/test-distro.py
Replace code sequence with data definition.
I selected Clover-v2.4k-4411-X64.iso and got a big chunk of output because the iso contains rather large number of files.
=> Avoid logging unbounded amount of info.

scripts/install.py, scripts/syslinux.py, scripts/update_cfg_file.py
Please see the commit messages for details.
@mbusb, what is the reason that let you apply syslinux module replacement only to debian?
Would not it make sense to do the same for all distros?
=> Address issues with Manjaro, Slitaz-rolloing and Salix-Live

scripts/update_cfg_file.py
in Manjaro 17.0 syslinux booting. See https://github.com/mbusb/multibootusb/issues/329
=> Hunt gfxboot.c32 hidden under a path-prefix, which fixes the hang

scripts/grub.py
loopback.cfg so that one for i686 won't hide another for x86_64
or vice versa.
=> Postfix menu-entry with an architecture name when generating

scripts/gen.py, scripts/install.py, scripts/qemu.py
Fix exception from install_patch() raised when a distro does not have isolinux_bin_dir.
Support an alternate bios when running QEMU.
Try relative paths first before /usr/share/multibootusb when locating a resource.
=> Fix exception from install_path() and other enhancements

scripts/install.py, scripts/update_cfg_file.py
Perhaps the failure of mounting (the root device?) reported in https://github.com/mbusb/multibootusb/issues/288 is due to  the use of a device name.
=> gentoo related fixes

scripts/mbusb_gui.py
because syslinux does not seem to be able to handle a pathname that contains space(s).
=> Refuse to process an iso file whose name contains space(s)

multibootusb
Catching all exception types obscures exceptions that are not anticipated.
@mbusb, please suggest amendments if this does not achieve what you intended.
(Would it not be possible to remove all import retries? )
=> Avoid catch-all exception handling.

scripts/install.py
Fix typo in a log message.
Perform syslinux module replacement for ubuntu.
Remove no-op assignment.
=> Log OSError/IOError while attempting to unlzma syslinux modules.

scripts/imager.py, scripts/mbusb_gui.py, scripts/osdriver.py, scripts/syslinux.py, scripts/udisks.py, scripts/usb.py
Handle exception raised during imaging.
Unify progress display between Windows and Linux.
Move platform dependent code to osdriver.py
Unmount all partitions that belongs to the drive being written to.
Write to \\.\\PhysicalDriveX  instead of  \\.\X: on Windows (**but the operation fails at the moment**)
Add warning about dding MBR.
Avoid using reserved keyword 'type' as a variable name.
=> Fix on Imager and add warning about running 'mbr_install_cmd'.

scripts/osdriver.py
Copying of syslinux boot code fails without this.
=> Fix bug of not having osdriver.Windows.add_dd_args() defined.

scripts/mbusb_cli.py
The CLI uninstall procedure was calling a nonexistent function to do the actual uninstall.  Replaced this call with a call to `do_uninstall_distro()`.  Appears to work.
Should fix issue #409.
=> Call correct function to uninstall. Fixes issue #409.

scripts/update_cfg_file.py
Fixes issue #414, possibly others.  isolinux.cfg was not being renamed when it was not all-lowercase.
=> rename isolinux.cfg to syslinux.cfg in a case-insensitive way

scripts/gen.py, scripts/mbusb_cli.py, scripts/mbusb_gui.py, scripts/osdriver.py, scripts/syslinux.py, scripts/usb.py
This implements better handling of device node paths, removing the errors when selecting "all drives" while there are loop devices or disks with >9 partitions and making it possible to install iso's to those devices. I tested this on Linux and Windows without any errors.
=> properly handle loop device paths

scripts/grub.py, scripts/update_cfg_file.py
Works cleanly with Mageia 7, which no longer uses isolinux. Mageia 6.1
can be booted using grub2, albeit only with a text menu, but syslinux
boot is still broken.
=> Fix Mageia support.

data/multibootusb/grub/win.cfg, scripts/distro.py, scripts/update_cfg_file.py
Fix detection of Windows ISO.
Fix Windows boot in UEFI mode: boot to Windows from grub by chainloading Windows ISO's bootx64.efi instead of bootmgr.efi.
=> Fix issue #459 and #439
