mbusb/multibootusb

multibootusb
Added updating the usb disk info after install/uninstall
=> Added updating the usb disk info after install/uninstall

multibootusb, scripts/admin.py, scripts/qemu.py, scripts/syslinux.py
Biggest problem is sudo issues: incorrect flags made it impossible to complete the install
(Note: running on Fedora 23 x64, if that matters)
Added pkexec (sudo-like command), also fixed a couple of GUI errors
=> Several fixes (sudo calls, GUI weirdness)

scripts/mbusb_gui.py
regarding 0e73b8b and 7c98ec0, use dict.get(key) with safe defaults instead of dict[key]
=> Safely access usb info dict

scripts/distro.py, scripts/grub.py, scripts/install.py, scripts/isodump3.py, scripts/mbusb_gui.py, scripts/persistence.py, scripts/syslinux.py, scripts/update_cfg_file.py
9923b57 fix persistence on mount points containing spaces
374d494 fix typos and reword
=> various fixes

multibootusb, scripts/colorama/__init__.py, scripts/colorama/ansi.py, scripts/colorama/ansitowin32.py, scripts/colorama/initialise.py, scripts/colorama/win32.py, scripts/colorama/winterm.py, scripts/config.py, scripts/debug.py, scripts/install.py
- bundled Colorama module (https://pypi.python.org/pypi/colorama)
- add initial debug API using ANSI colors
- reduce redundant function calls
=> Fixes & additions

scripts/mbusb_gui.py
It crashed on startup.
So it works with PyQt4 too.
http://stackoverflow.com/a/22619556/1951027
=> Update msgBox.exec() to msgBox.exec_()

scripts/iso.py, scripts/isodump3.py, scripts/mbusb_gui.py
change 3-space indent to 4-space in isodump3.py
Fix another spacing issue nearby.
=> Fix inconsistent indentation

scripts/update_cfg_file.py
=> Fix parted magic grub label

scripts/syslinux.py
When installing a distro, I get following error messages towards the end of installation.
> Default syslinux install is success...
> 
> Replacing efi binary with msdos compatible one...
> [Errno 2] No such file or directory: 'G:\\EFI\\BOOT\\bootx64-msdos.efi'
> Failed to replace efi binary...
> Replacing core.img with msdos compatible one...
> [Errno 2] No such file or directory: 'G:\\multibootusb\\grub\\core-msdos.img'
> Failed to replace core.img binary...
It seems these files were removed by commit  https://github.com/mbusb/multibootusb/commit/ec0f8d95f98f65541c8734623d97f4bd3cbecf0f. This patch avoids getting the error messages issued by checking existence of the source files before attempting a copy.
=> Avoid trying to update bootx64.efi and grub.img if source files are missing.

.gitignore, CHANGELOG, build_pkg, scripts/gen.py, scripts/qemu.py, scripts/syslinux.py, scripts/update_cfg_file.py, scripts/usb.py, setup.py
It seems relevant commits are as follows.
89ca0a94cad83202c0057666c94d822db802aba5 New release - version 9.1.0
1139faa5b8b721ac20e054416641668eca5b8d22 Fix parted magic grub label
7657e7c70cb289bdce91199f2c069fe19944a493 Fixed dependency of get_physical_disk_number() ...
07a0601a9a6c37ea2f7c00527808aa3329d21cfe Simplify implementation of get_physical_drive() ...
1ac993077dea85381ca1a85db0929ffd25558597 Have gpt_device() use 'wmi' module rather than ...
31a08eeb642843a111e670d5f753320a0ccad69d Avoid updating bootx64.efi and grub.img ...
=> Merged from master.

scripts/install.py
regarding 'Avira-RS' installation. That is, shutil.move(,f) is conditioned on
os.path.exists(f).
Tested with trinitiy-rescute-kit. Unfortunately I could not test with Avira-RS as the version I could find was based on ubunu.
=> Replace a common code-block with a method call, which also fixes a bug

scripts/grub.py, scripts/mbusb_gui.py
Please see the commit message for https://github.com/mbusb/multibootusb/commit/8ea5932bdcd706d7ca4c8b44aa7b0a424daec59d about the deails of the latter.
Though I have tested with anergos-18.3-86_64.iso and debian-live-9.4.0-amd64-cinnamon.iso and will try more, I'd appreciate if you review the changes and kick tires before merging.
=> Fix failure of syslinux installation on the usb stick and enhance generation of loopback.cfg

scripts/update_cfg_file.py
Print "/dev/ram0 is kept as is.  [8]" instead of 8 lines of "/dev/ram0 is kept as is".
=> Log path rewriting exceptions in more concise manner.

scripts/update_cfg_file.py
manner.
Fix path finding regular expression to properly catch comma-delimited
paths.
Avoid rewriting paths on a comment line. 
Minor change of logged messages about path rewriting.
=> Report non-existent file references in config files in more concise

scripts/mbusb_gui.py
misunderstand that the distro does not implement persistence at all.
=> Change wording of a message slightly so that a user will not

scripts/update_cfg_file.py
Tested using antiX-17.1_386-core.iso. Though booting hangs "waiting for /dev to be fully poplulated" under QEMU but boots up fine on a bare metal.
=> Add support for AntiX 17.1

multibootusb, scripts/mbusb_cli.py, scripts/mbusb_gui.py
* Prevent mbusb_cli from installing over existing installation.
* Support persistence size specification in mbusb_cli.
* Line break adjustment to fit 80 cols at relevant places.
=> CLI enhancements

multibootusb
Sending out of my 'devel' branch as one from 'cli_fix' went haywire.
=> Allow target drive specification using lower case letter.

scripts/usb.py
* Because 'Extended' is sought over entire output of /dev/sdc, /dev/sdc gets determined as extended partition if it contains an extended partition.
* Obtain type of /dev/sdc2 by examining output of _fdisk -l /dev/sdc_. It seems  _fdisk -l /dev/sdc2_ does not tell the partition type of the specified partition but shows pseudo partitions obtained by looking at the first sector of /dev/sdc2.
* Force C locale when running fdisk. Extendended partition is marked by '拡張領域' in ja_JP locale, for example.
* Detect swap partition as well.
* Renamed a global variable from 'u' to 'UDISKS'.
=>  FIX/improve partition type detection. 

scripts/gen.py
Deduplicate common path expression.
=> Remove redundant list comprehension.

scripts/config.py, scripts/qemu.py
* Support accelaration via Intel HAXM hypervisor.
* Provide more flexibility in selecting which qemu to run.
* Fix multiple calls to check_qemu_exist().
=> QEMU related enhancements.

scripts/config.py, scripts/mbusb_gui.py
variable by not showing them in the target drive listbox.
Ideally this should be configurable via GUI.
=> Allow protection of drives through 'config.protected_drives'

scripts/update_cfg_file.py
The distro is mentioned in issue https://github.com/mbusb/multibootusb/issues/341
=> Fix booting of MX-17.1 (an antiX derivative).

scripts/update_cfg_file.py
Prepare for antiX/MX version 18 and beyond.
=> Deal with MX iso that lacks 'version' file.

scripts/config.py, scripts/mbusb_gui.py
config.image_path defaults to '' in config.py but it's set to None in AppGui.__init__().
=> Fix exception from os.path.basename(None).

setup.py
See https://github.com/mbusb/multibootusb/issues/336
=> Add gptmbr.bin to package data files

scripts/osdriver.py, scripts/usb.py
* avoid zero-suppression
* avoid truncation of upper 32 bits of NTFS serial number.
Tested writing onto FAT32 stick installing Antergos. Test on NTFS is appreciated.
=> Fix uuid generation from NTFS/FAT32 partition on Windows.

scripts/gen.py, scripts/imager.py, scripts/osdriver.py, scripts/udisks.py
Disable assignment to 'config.imager_return' as it is not used elsewhere yet.
=> Unify imager code again.

scripts/imager.py, scripts/osdriver.py
Rename variables and fix a comment for clarity.
Fix syntax of an exception description.
=> Log the last 16(max) lines of dd output.

scripts/mbusb_gui.py, scripts/osdriver.py, scripts/persistence.py, scripts/usb.py
Fix repeated calls to self.ui.combo_drives.setCurrentIndex(0) when refreshing the combo-box.
Wait for command completion when checking tool availability.
This should fix issue https://github.com/mbusb/multibootusb/issues/380
=> Fix hang from parted not exiting. (See issue 380 for details.)

multibootusb, scripts/imager.py, scripts/mbusb_gui.py, scripts/osdriver.py, scripts/qemu.py, scripts/usb.py, scripts/win32.py
Show physical drives on Windows too.
Unmount partitions and lock physical drive when dd-ing iso on Windows
Reset progress before starting dd-iso thread.
Relocate call site for pythocom.CoInitialize()
There some remaining edges to be ground, dd-ing works much more reliably in my environment.
=> New implementaion of image dd-ing on Windows.

scripts/mbusb_gui.py
As we discussed in issue #397,  this is a conversion to spaces from tabs for mbusb_gui.py so that it matches the rest of the project.
=> Replace tabs with spaces to match the rest of the project

multibootusb
=> Fix SyntaxWarning for python 3.8.0
